// ─── Primitives ──────────────────────────────────────────────────────────────

export type DurabilityMode = 'volatile' | 'durable';
export type QueueFullBehavior = 'dlq' | 'drop';
export type TenancyMode = 'single_database' | 'database_per_tenant';

// Re-export reliability types for consumers of logbun root
export type {
  ReliabilityAdapter,
  DLQEntry,
  ClaimedDlqBatch,
  JournalRecoveryResult,
  ReliabilityStats,
  DlqState,
} from './reliability/types';

import type { ReliabilityAdapter } from './reliability/types';

// ─── Log Shape ───────────────────────────────────────────────────────────────

/** Input from the developer — no id, no timestamps, no request context */
export interface LogbunLogInput<TAction extends string = string> {
  tenantId?: string;
  actorId: string;
  action: TAction;
  entityId?: string;
  oldValues?: Record<string, unknown>;
  newValues?: Record<string, unknown>;
  metadata?: Record<string, unknown>;
}

/** Stored record — library-generated fields are added here */
export interface LogbunLog<TAction extends string = string>
  extends LogbunLogInput<TAction> {
  id: string; // UUIDv7 (RFC 9562 via Web Crypto)
  createdAt: string; // ISO 8601 UTC (generated by the library)
  ipAddress?: string; // Injected by Framework Plugin
  userAgent?: string; // Injected by Framework Plugin
  /**
   * Integrity hash chain (when `integrityChain` is enabled).
   * `prevHash` links to the previous sealed log's `contentHash` (genesis = 64 zero hex).
   */
  prevHash?: string;
  /** SHA-256 hex of `prevHash + '\\n' + canonical payload` when integrity is on. */
  contentHash?: string;
}

// ─── Query Contract ──────────────────────────────────────────────────────────

export interface LogbunQueryFilters<TAction extends string = string> {
  action?: TAction;
  actorId?: string;
  entityId?: string;
  startDate?: string; // ISO 8601
  endDate?: string;
}

export interface LogbunQueryResult<TAction extends string = string> {
  logs: LogbunLog<TAction>[];
  nextCursor: string | null; // null means no more pages
}

// ─── Events ──────────────────────────────────────────────────────────────────

export type LogbunEventType =
  | 'enqueue'
  | 'flush_ok'
  | 'flush_fail'
  | 'dlq'
  | 'drop'
  | 'truncated'
  | 'wal_fail'
  | 'bootstrap_fail'
  | 'prune_fail'
  | 'poison'
  | 'degraded'
  | 'stats'
  | 'limit';

/** Lightweight observability event emitted via LogbunConfig.onEvent */
export interface LogbunEvent {
  type: LogbunEventType;
  tenantId?: string | null;
  error?: string;
  count?: number;
  detail?: string;
}

// ─── Configuration ───────────────────────────────────────────────────────────

export interface BatchingConfig {
  maxSize: number; // Flush when queue reaches this count
  flushInterval: number; // Flush after this ms (whichever comes first)
  maxQueueSize: number; // Backpressure threshold
  onQueueFull: QueueFullBehavior;
}

/**
 * Multi-tenant routing configuration.
 *
 * Prefer {@link LogbunConfig.adapterFactory} for pool recreation of per-tenant
 * adapters; `resolveConnection` remains for connection-config resolution.
 */
export interface TenancyConfig {
  mode: TenancyMode;
  resolveConnection?: (
    tenantId: string
  ) => Promise<Record<string, unknown> | null>;
  /**
   * Tenant ids known to the control plane — used by retention prune in
   * `database_per_tenant` mode so cold tenants (not in the live pool) are still pruned.
   */
  knownTenantIds?: () => string[] | Promise<string[]>;
}

/**
 * Retention policy. Hosts schedule pruning via {@link AuditLogger.runMaintenance};
 * there is no built-in cron timer.
 */
export interface RetentionConfig {
  days: number;
}

/**
 * Retry / bulk-insert tuning. Hosts schedule DLQ retries via
 * {@link AuditLogger.runMaintenance} (or {@link AuditLogger.retryDlqNow}).
 * Recurring scan timers were removed in 1.0.
 */
export interface RetryConfig {
  /** Scan-level failures before poison. @default 10 */
  maxScanAttempts?: number;
  /**
   * Total bulkInsert attempts per flush/scan (includes the first try).
   * Engine loops `for (let attempt = 0; attempt < insertMaxRetries; attempt++)`.
   * @default 3 — three total tries, not “3 retries after first”
   */
  insertMaxRetries?: number;
  /** Base backoff delay in ms (doubles each retry). @default 1_000 */
  insertBaseDelayMs?: number;
}

/**
 * Recommended settings for multi-tenant / enterprise SaaS.
 * Library defaults stay looser for back-compat; copy these into config for production.
 */
export const ENTERPRISE_DEFAULTS = {
  mode: 'durable' as const,
  requireTenantId: true,
} as const;

export interface LogbunConfig<TActions extends string> {
  /** Isolates reliability storage per instance. Required for multi-instance setups. */
  namespace: string;
  /**
   * `volatile` (default): in-memory reliability; process death can lose queued work.
   * `durable`: requires a **persistent** {@link reliability} adapter
   * (e.g. FileReliabilityAdapter or CloudflareReliabilityAdapter). Missing or
   * non-persistent reliability is rejected synchronously in the constructor.
   */
  mode?: DurabilityMode;
  /**
   * Reliability backend (journal + DLQ).
   * - Volatile default: MemoryReliabilityAdapter (created internally if omitted)
   * - Durable: required, must have `persistent: true`
   */
  reliability?: ReliabilityAdapter;
  adapter: IAdapter;
  tenancy?: TenancyConfig;
  batching?: Partial<BatchingConfig>;
  retention?: RetentionConfig;
  pool?: {
    maxActiveConnections?: number; // Default: 50
  };
  /** DLQ retry / bulk-insert tuning. */
  retry?: RetryConfig;

  /** Optional observability hook for lifecycle events (flush, dlq, drop, …). */
  onEvent?: (e: LogbunEvent) => void;

  /**
   * When true, fire/query require a non-empty tenantId.
   * Automatically true when `tenancy.mode === 'database_per_tenant'`.
   * For multi-tenant SaaS on `single_database`, set this to `true`.
   * @default false — single-tenant / back-compat only; keep false unless multi-tenant
   */
  requireTenantId?: boolean;

  /**
   * Max concurrent queue keys (in-memory tenant map size).
   * @default 10_000
   */
  maxActiveTenants?: number;

  /**
   * Global cap: sum of all per-tenant queue lengths + reservations.
   * @default 50_000
   */
  maxTotalQueued?: number;

  /**
   * Max wait (ms) per bulkInsert attempt path in flushAll / shutdown.
   * @default 30_000
   */
  flushTimeoutMs?: number;

  /**
   * Hard cap on query page size.
   * @default 500
   */
  maxQueryLimit?: number;

  /**
   * Max serialized log payload size in bytes (oldValues/newValues/metadata).
   * @default 64_000
   */
  maxPayloadBytes?: number;

  /**
   * Max UTF-8 bytes for scalar string fields (actorId, action, entityId,
   * userAgent, ipAddress). tenantId is never capped (routing identity).
   * Oversized values are truncated.
   * @default 2_048
   */
  maxStringFieldBytes?: number;

  /**
   * Max logs accepted before bootstrap completes (pre-ready buffer).
   * Excess is dropped with a `drop` event.
   * @default 10_000
   */
  maxPreReadyBuffer?: number;

  /**
   * Max logs injected from journal recovery into RAM at once.
   * Remaining entries stay durable and are injected after flushes drain.
   * @default maxQueueSize (from batching) or 1_000
   */
  maxRecoveryBatch?: number;

  /**
   * Max concurrent bulkInsert flushes globally (batcher semaphore).
   * @default 16
   */
  maxFlushConcurrency?: number;

  /**
   * Seal each log into a hash chain (`prevHash` / `contentHash`) for
   * tamper evidence. Not WORM object storage — detection only.
   * @default false
   */
  integrityChain?: boolean;

  /**
   * Dot-paths into oldValues / newValues / metadata to redact before persist.
   * Supports deep paths: `metadata.user.ssn`, bare keys, and bag prefixes.
   * Example: `['password', 'metadata.ssn', 'newValues.token']`
   */
  redactPaths?: string[];

  /**
   * Factory used to (re)create per-tenant adapters from resolved connection
   * config. Preferred over only using TenancyConfig.resolveConnection when
   * the pool must rebuild adapters (database_per_tenant).
   */
  adapterFactory?: (
    config: Record<string, unknown>
  ) => IAdapter | Promise<IAdapter>;
}

// ─── Adapter Interface ───────────────────────────────────────────────────────

export interface IAdapter {
  init(): Promise<void>;

  /**
   * @returns true on success, false to route the batch to the DLQ.
   * Prefer throwing on unexpected failures so the engine can emit `error` text;
   * returning false is treated as a soft/retryable failure.
   */
  bulkInsert(tenantId: string | null, logs: LogbunLog[]): Promise<boolean>;

  query(
    tenantId: string | null,
    filters: LogbunQueryFilters,
    pagination: { cursor?: string; limit: number }
  ): Promise<LogbunQueryResult>;

  /**
   * ClickHouse: executes DROP PARTITION for expired months.
   * SQLite/Turso: executes DELETE WHERE created_at < cutoff.
   */
  prune(days: number): Promise<void>;

  close(): Promise<void>;
}

// ─── Plugin Context ──────────────────────────────────────────────────────────

/**
 * Populated automatically by Framework Plugins — not exposed to the developer.
 *
 * On request-scoped runtimes (Workers, serverless), pass `waitUntil` so
 * {@link AuditLogger.fire} registers its admission task with the host.
 * Volatile delivery still requires `fireAsync()` + `flush()` for correctness
 * when the isolate may exit; durable DO journal admission survives termination.
 */
export interface LogbunRequestContext {
  ipAddress?: string;
  userAgent?: string;
  /**
   * Host waitUntil (e.g. Cloudflare Workers ExecutionContext.waitUntil).
   * Listener/host errors never break the audit pipeline.
   */
  waitUntil?: (task: Promise<unknown>) => void;
}
