// ─── Primitives ──────────────────────────────────────────────────────────────

export type DurabilityMode = 'volatile' | 'durable';
export type QueueFullBehavior = 'dlq' | 'drop';
export type TenancyMode = 'single_database' | 'database_per_tenant';

// ─── Log Shape ───────────────────────────────────────────────────────────────

/** Input from the developer — no id, no timestamps, no request context */
export interface LogbunLogInput<TAction extends string = string> {
  tenantId?: string;
  actorId: string;
  action: TAction;
  entityId?: string;
  oldValues?: Record<string, unknown>;
  newValues?: Record<string, unknown>;
  metadata?: Record<string, unknown>;
}

/** Stored record — library-generated fields are added here */
export interface LogbunLog<TAction extends string = string>
  extends LogbunLogInput<TAction> {
  id: string;          // UUIDv7 (generated by the library via Bun.randomUUIDv7())
  createdAt: string;   // ISO 8601 UTC (generated by the library)
  ipAddress?: string;  // Injected by Framework Plugin
  userAgent?: string;  // Injected by Framework Plugin
}

// ─── Query Contract ──────────────────────────────────────────────────────────

export interface LogbunQueryFilters<TAction extends string = string> {
  action?: TAction;
  actorId?: string;
  entityId?: string;
  startDate?: string;  // ISO 8601
  endDate?: string;
}

export interface LogbunQueryResult<TAction extends string = string> {
  logs: LogbunLog<TAction>[];
  nextCursor: string | null;  // null means no more pages
}

// ─── Configuration ───────────────────────────────────────────────────────────

export interface BatchingConfig {
  maxSize: number;              // Flush when queue reaches this count
  flushInterval: number;        // Flush after this ms (whichever comes first)
  maxQueueSize: number;         // Backpressure threshold
  onQueueFull: QueueFullBehavior;
}

export interface TenancyConfig {
  mode: TenancyMode;
  resolveConnection?: (tenantId: string) => Promise<Record<string, unknown> | null>;
}

export interface RetentionConfig {
  days: number;
  /**
   * Standard 5-field cron expression (no seconds field).
   * @default '0 0 * * *' — daily at midnight
   */
  cronExpression?: string;
}

export interface LogbunConfig<TActions extends string> {
  /** Isolates WAL and DLQ files per instance. Required for multi-instance setups. */
  namespace: string;
  mode?: DurabilityMode;        // Default: 'volatile'
  adapter: IAdapter;
  tenancy?: TenancyConfig;
  batching?: Partial<BatchingConfig>;
  retention?: RetentionConfig;
  pool?: {
    maxActiveConnections?: number; // Default: 50
  };
}

// ─── Adapter Interface ───────────────────────────────────────────────────────

export interface IAdapter {
  init(): Promise<void>;

  /**
   * @returns true on success, false to route the batch to the DLQ
   */
  bulkInsert(tenantId: string | null, logs: LogbunLog[]): Promise<boolean>;

  query(
    tenantId: string | null,
    filters: LogbunQueryFilters,
    pagination: { cursor?: string; limit: number }
  ): Promise<LogbunQueryResult>;

  /**
   * ClickHouse: executes DROP PARTITION for expired months.
   * SQLite/Turso: executes DELETE WHERE created_at < cutoff.
   */
  prune(days: number): Promise<void>;

  close(): Promise<void>;
}

// ─── Plugin Context ──────────────────────────────────────────────────────────

/** Populated automatically by Framework Plugins — not exposed to the developer */
export interface LogbunRequestContext {
  ipAddress?: string;
  userAgent?: string;
}
