// ─── Primitives ──────────────────────────────────────────────────────────────

export type DurabilityMode = 'volatile' | 'durable';
export type QueueFullBehavior = 'dlq' | 'drop';
export type TenancyMode = 'single_database' | 'database_per_tenant';

// ─── Log Shape ───────────────────────────────────────────────────────────────

/** Input from the developer — no id, no timestamps, no request context */
export interface LogbunLogInput<TAction extends string = string> {
  tenantId?: string;
  actorId: string;
  action: TAction;
  entityId?: string;
  oldValues?: Record<string, unknown>;
  newValues?: Record<string, unknown>;
  metadata?: Record<string, unknown>;
}

/** Stored record — library-generated fields are added here */
export interface LogbunLog<TAction extends string = string>
  extends LogbunLogInput<TAction> {
  id: string; // UUIDv7 (generated by the library via Bun.randomUUIDv7())
  createdAt: string; // ISO 8601 UTC (generated by the library)
  ipAddress?: string; // Injected by Framework Plugin
  userAgent?: string; // Injected by Framework Plugin
  /**
   * Integrity hash chain (when `integrityChain` is enabled).
   * `prevHash` links to the previous sealed log's `contentHash` (genesis = 64 zero hex).
   */
  prevHash?: string;
  /** SHA-256 hex of `prevHash + '\\n' + canonical payload` when integrity is on. */
  contentHash?: string;
}

// ─── Query Contract ──────────────────────────────────────────────────────────

export interface LogbunQueryFilters<TAction extends string = string> {
  action?: TAction;
  actorId?: string;
  entityId?: string;
  startDate?: string; // ISO 8601
  endDate?: string;
}

export interface LogbunQueryResult<TAction extends string = string> {
  logs: LogbunLog<TAction>[];
  nextCursor: string | null; // null means no more pages
}

// ─── Events ──────────────────────────────────────────────────────────────────

export type LogbunEventType =
  | 'enqueue'
  | 'flush_ok'
  | 'flush_fail'
  | 'dlq'
  | 'drop'
  | 'truncated'
  | 'wal_fail'
  | 'bootstrap_fail'
  | 'prune_fail'
  | 'poison'
  | 'degraded'
  | 'stats'
  | 'limit';

/** Lightweight observability event emitted via LogbunConfig.onEvent */
export interface LogbunEvent {
  type: LogbunEventType;
  tenantId?: string | null;
  error?: string;
  count?: number;
  detail?: string;
}

// ─── Configuration ───────────────────────────────────────────────────────────

export interface BatchingConfig {
  maxSize: number; // Flush when queue reaches this count
  flushInterval: number; // Flush after this ms (whichever comes first)
  maxQueueSize: number; // Backpressure threshold
  onQueueFull: QueueFullBehavior;
}

/**
 * Multi-tenant routing configuration.
 *
 * Prefer {@link LogbunConfig.adapterFactory} for pool recreation of per-tenant
 * adapters; `resolveConnection` remains for connection-config resolution.
 */
export interface TenancyConfig {
  mode: TenancyMode;
  resolveConnection?: (
    tenantId: string
  ) => Promise<Record<string, unknown> | null>;
  /**
   * Tenant ids known to the control plane — used by retention prune in
   * `database_per_tenant` mode so cold tenants (not in the live pool) are still pruned.
   */
  knownTenantIds?: () => string[] | Promise<string[]>;
}

export interface RetentionConfig {
  days: number;
  /**
   * Standard 5-field cron expression (no seconds field).
   * @default '0 0 * * *' — daily at midnight
   */
  cronExpression?: string;
}

export interface RetryConfig {
  /** Interval between DLQ scans in ms. @default 60_000 */
  scanIntervalMs?: number;
  /** Delay before first scan after bootstrap. @default 10_000 */
  initialDelayMs?: number;
  /** Scan-level failures before poison. @default 10 */
  maxScanAttempts?: number;
  /**
   * Total bulkInsert attempts per flush/scan (includes the first try).
   * Engine loops `for (let attempt = 0; attempt < insertMaxRetries; attempt++)`.
   * @default 3 — three total tries, not “3 retries after first”
   */
  insertMaxRetries?: number;
  /** Base backoff delay in ms (doubles each retry). @default 1_000 */
  insertBaseDelayMs?: number;
}

export interface WalConfig {
  /**
   * fsync after each WAL append and compact rewrite.
   * Stronger durability (power-loss safer); higher latency.
   * @default true when mode is `durable`
   */
  fsync?: boolean;
  /**
   * Compact (rewrite) the WAL after this many acknowledged ids have accumulated
   * in the sidecar, or when remaining size warrants it.
   * @default 256
   */
  compactAckThreshold?: number;
  /**
   * Rotate `current.aof` into a sealed segment at this size (bytes).
   * Bounds compact/read peak memory closer to segment size.
   * @default 16 * 1024 * 1024 (16 MiB)
   */
  segmentBytes?: number;
  /**
   * When true (default), refuse WAL append once total size >= maxWalBytes
   * (`wal_full` → batcher DLQ fallback). Set false for soft-only guidance.
   * @default true
   */
  hardMaxBytes?: boolean;
}

/**
 * Recommended settings for multi-tenant / enterprise SaaS.
 * Library defaults stay looser for back-compat; copy these into config for production.
 */
export const ENTERPRISE_DEFAULTS = {
  mode: 'durable' as const,
  requireTenantId: true,
} as const;

export interface LogbunConfig<TActions extends string> {
  /** Isolates WAL and DLQ files per instance. Required for multi-instance setups. */
  namespace: string;
  mode?: DurabilityMode; // Default: 'volatile'
  adapter: IAdapter;
  tenancy?: TenancyConfig;
  batching?: Partial<BatchingConfig>;
  retention?: RetentionConfig;
  pool?: {
    maxActiveConnections?: number; // Default: 50
  };
  /** DLQ retry engine tuning. */
  retry?: RetryConfig;
  /** WAL durability options (only used when mode is `durable`). */
  wal?: WalConfig;

  /**
   * Root directory for WAL/DLQ data. Namespace is joined under this root.
   * Default: `.logbun`
   */
  dataDir?: string;

  /** Optional observability hook for lifecycle events (flush, dlq, drop, …). */
  onEvent?: (e: LogbunEvent) => void;

  /**
   * When true, fire/query require a non-empty tenantId.
   * Automatically true when `tenancy.mode === 'database_per_tenant'`.
   * For multi-tenant SaaS on `single_database`, set this to `true`.
   * @default false — single-tenant / back-compat only; keep false unless multi-tenant
   */
  requireTenantId?: boolean;

  /**
   * Max concurrent queue keys (in-memory tenant map size).
   * @default 10_000
   */
  maxActiveTenants?: number;

  /**
   * Global cap: sum of all per-tenant queue lengths + reservations.
   * @default 50_000
   */
  maxTotalQueued?: number;

  /**
   * Max wait (ms) per bulkInsert attempt path in flushAll / shutdown.
   * @default 30_000
   */
  flushTimeoutMs?: number;

  /**
   * fsync DLQ batch files after write / attempt updates.
   * @default true when mode is `durable`, otherwise false
   */
  dlqFsync?: boolean;

  /**
   * Hard cap on query page size.
   * @default 500
   */
  maxQueryLimit?: number;

  /**
   * Max serialized log payload size in bytes (oldValues/newValues/metadata).
   * @default 64_000
   */
  maxPayloadBytes?: number;

  /**
   * Max UTF-8 bytes for scalar string fields (actorId, action, entityId,
   * userAgent, ipAddress). tenantId is never capped (routing identity).
   * Oversized values are truncated.
   * @default 2_048
   */
  maxStringFieldBytes?: number;

  /**
   * Max logs accepted before bootstrap completes (pre-ready buffer).
   * Excess is dropped with a `drop` event.
   * @default 10_000
   */
  maxPreReadyBuffer?: number;

  /**
   * Max logs injected from WAL recovery into RAM at once.
   * Remaining entries stay on disk and are injected after flushes drain.
   * @default maxQueueSize (from batching) or 1_000
   */
  maxRecoveryBatch?: number;

  /**
   * Max concurrent bulkInsert flushes globally (batcher semaphore).
   * @default 16
   */
  maxFlushConcurrency?: number;

  /**
   * WAL size limit in bytes (recovery guidance + hard/soft append policy).
   * When `wal.hardMaxBytes` is true (default), append throws `wal_full` at/over
   * this size and the batcher falls back to DLQ. Set `wal.hardMaxBytes: false`
   * for soft-only guidance (append still succeeds; observe via approximateSize /
   * `getStatsDetailed().walApproxBytes`).
   * @default 64 * 1024 * 1024 (64 MiB)
   */
  maxWalBytes?: number;

  /**
   * Optional alias for {@link maxWalBytes}. Prefer `maxWalBytes`.
   * @default same as maxWalBytes (64 MiB)
   */
  walSoftLimitBytes?: number;

  /**
   * Refuse new DLQ writes when pending + processing file count is >= this.
   * Dead files do not count against the write cap (ops can clean them).
   * @default 10_000
   */
  maxDlqFiles?: number;

  /**
   * AES-256-GCM at-rest encryption for local WAL lines and DLQ batch files.
   * Accepts 32-byte `Uint8Array`, 64-char hex, base64 of 32 bytes, or a
   * passphrase (SHA-256 hashed — prefer a full-entropy key in production).
   * When set, ciphertext is stored; plaintext never written to WAL/DLQ.
   */
  encryptionKey?: string | Uint8Array;

  /**
   * Seal each log into a hash chain (`prevHash` / `contentHash`) for
   * tamper evidence. Not WORM object storage — detection only.
   * @default false
   */
  integrityChain?: boolean;

  /**
   * Acquire an exclusive multi-process lock on the namespace data dir so two
   * replicas cannot share the same local WAL/DLQ. Recommended for durable mode.
   * @default true when mode is `durable`, otherwise false
   */
  instanceLock?: boolean;

  /**
   * Dot-paths into oldValues / newValues / metadata to redact before persist.
   * Supports deep paths: `metadata.user.ssn`, bare keys, and bag prefixes.
   * Example: `['password', 'metadata.ssn', 'newValues.token']`
   */
  redactPaths?: string[];

  /**
   * Factory used to (re)create per-tenant adapters from resolved connection
   * config. Preferred over only using TenancyConfig.resolveConnection when
   * the pool must rebuild adapters (database_per_tenant).
   */
  adapterFactory?: (
    config: Record<string, unknown>
  ) => IAdapter | Promise<IAdapter>;
}

// ─── Adapter Interface ───────────────────────────────────────────────────────

export interface IAdapter {
  init(): Promise<void>;

  /**
   * @returns true on success, false to route the batch to the DLQ.
   * Prefer throwing on unexpected failures so the engine can emit `error` text;
   * returning false is treated as a soft/retryable failure.
   */
  bulkInsert(tenantId: string | null, logs: LogbunLog[]): Promise<boolean>;

  query(
    tenantId: string | null,
    filters: LogbunQueryFilters,
    pagination: { cursor?: string; limit: number }
  ): Promise<LogbunQueryResult>;

  /**
   * ClickHouse: executes DROP PARTITION for expired months.
   * SQLite/Turso: executes DELETE WHERE created_at < cutoff.
   */
  prune(days: number): Promise<void>;

  close(): Promise<void>;
}

// ─── Plugin Context ──────────────────────────────────────────────────────────

/** Populated automatically by Framework Plugins — not exposed to the developer */
export interface LogbunRequestContext {
  ipAddress?: string;
  userAgent?: string;
}

// ─── DLQ ops ─────────────────────────────────────────────────────────────────

export interface DLQFileInfo {
  path: string;
  kind: 'pending' | 'processing' | 'dead';
  tenantId: string | null;
  attempts: number;
  logCount: number;
}
